// Auxiliary profile used exclusively by the pump-flow calibration tool.
// Embedded (instead of loaded from the machine) so calibration runs are
// reproducible regardless of which profiles the user has stored.

export const CALIBRATION_PROFILE_ID = 'pump-flow-calibration';

export const CALIBRATION_PROFILE = {
  id: CALIBRATION_PROFILE_ID,
  label: '[Calibration] Pump flow calibration',
  type: 'pro',
  description: 'Auto-generated by the pump flow calibration tool.',
  temperature: 30,
  phases: [
    {
      name: 'Build 1 bar',
      phase: 'preinfusion',
      valve: 0,
      duration: 20,
      temperature: 0,
      transition: { type: 'ease-out', duration: 5, adaptive: true },
      pump: { target: 'pressure', pressure: 1, flow: 0 },
      targets: [{ type: 'pressure', operator: 'gte', value: 1 }],
    },
    {
      name: 'Settle 1 bar',
      phase: 'preinfusion',
      valve: 0,
      duration: 5,
      temperature: 0,
      transition: { type: 'instant', duration: 0, adaptive: true },
      pump: { target: 'pressure', pressure: 1, flow: 0 },
    },
    {
      name: 'Measure 1 bar',
      phase: 'brew',
      valve: 0,
      duration: 10,
      temperature: 25,
      transition: { type: 'instant', duration: 0, adaptive: true },
      pump: { target: 'pressure', pressure: 1, flow: 0 },
    },
    {
      name: 'Settle 1 bar',
      phase: 'brew',
      valve: 0,
      duration: 5,
      temperature: 0,
      transition: { type: 'instant', duration: 0, adaptive: true },
      pump: { target: 'pressure', pressure: 1, flow: 0 },
    },
    {
      name: 'Build 9 bar',
      phase: 'brew',
      valve: 0,
      duration: 20,
      temperature: 0,
      transition: { type: 'ease-out', duration: 5, adaptive: true },
      pump: { target: 'pressure', pressure: 9, flow: 0 },
      targets: [{ type: 'pressure', operator: 'gte', value: 9 }],
    },
    {
      name: 'Settle 9 bar',
      phase: 'brew',
      valve: 0,
      duration: 5,
      temperature: 0,
      transition: { type: 'instant', duration: 0, adaptive: true },
      pump: { target: 'pressure', pressure: 9, flow: 0 },
    },
    {
      name: 'Measure 9 bar',
      phase: 'brew',
      valve: 0,
      duration: 10,
      temperature: 25,
      transition: { type: 'instant', duration: 0, adaptive: true },
      pump: { target: 'pressure', pressure: 9, flow: 0 },
    },
    {
      name: 'Settle 9 bar',
      phase: 'brew',
      valve: 0,
      duration: 5,
      temperature: 0,
      transition: { type: 'instant', duration: 0, adaptive: true },
      pump: { target: 'pressure', pressure: 9, flow: 0 },
    },
  ],
};
