#!/usr/bin/env python3
"""Pack the built web UI into a single blob embedded in the display firmware.

The web bundle used to live in a LittleFS partition (``/w``) shared with the
user's profiles and shot history. That coupled UI updates to a full-filesystem
reflash that wiped user data and could leave a new firmware running against a
stale/partial filesystem. Instead we embed the (already gzipped) bundle into the
firmware app image, where it lands in ``.rodata.embedded`` -> DROM and is served
straight from memory-mapped flash. See GM-106.

This script produces three artifacts in the output directory:

* ``web_ui.bin``          -- every asset concatenated into one blob.
* ``web_ui_blob.S``       -- a tiny assembly stub that ``.incbin``s the blob into
                             ``.rodata.embedded`` under a fixed symbol
                             (``gWebUiBlobStart``), so we never depend on
                             objcopy's path-derived ``_binary_*`` names.
* ``web_ui_manifest.h``   -- the lookup table (url path, offset, length, content
                             type, gzip flag) consumed by WebUIPlugin.

Usage:
    embed_webui.py --src web/dist --out src/display/webassets
    embed_webui.py --out src/display/webassets --stub   # empty placeholder
"""

import argparse
import os
import sys

# Logical extension (after stripping a trailing .gz) -> Content-Type.
CONTENT_TYPES = {
    ".html": "text/html",
    ".js": "text/javascript",
    ".mjs": "text/javascript",
    ".css": "text/css",
    ".json": "application/json",
    ".webmanifest": "application/manifest+json",
    ".svg": "image/svg+xml",
    ".png": "image/png",
    ".jpg": "image/jpeg",
    ".jpeg": "image/jpeg",
    ".gif": "image/gif",
    ".ico": "image/x-icon",
    ".webp": "image/webp",
    ".woff": "font/woff",
    ".woff2": "font/woff2",
    ".ttf": "font/ttf",
    ".txt": "text/plain",
    ".map": "application/json",
}

INDEX_PATH = "/index.html"


def content_type_for(path):
    _, ext = os.path.splitext(path)
    return CONTENT_TYPES.get(ext.lower(), "application/octet-stream")


def collect_assets(src_dir):
    """Return a sorted list of (url_path, gzip, abs_file) for every file."""
    assets = []
    for root, _dirs, files in os.walk(src_dir):
        for name in files:
            abs_file = os.path.join(root, name)
            rel = os.path.relpath(abs_file, src_dir).replace(os.sep, "/")
            gzip = rel.endswith(".gz")
            logical = rel[:-3] if gzip else rel
            assets.append(("/" + logical, gzip, abs_file))
    # Stable order keeps the generated blob/manifest reproducible across builds.
    assets.sort(key=lambda a: a[0])
    return assets


def c_escape(text):
    return text.replace("\\", "\\\\").replace('"', '\\"')


def write_artifacts(out_dir, entries, blob, blob_path):
    """entries: list of dicts {path, offset, length, content_type, gzip}."""
    os.makedirs(out_dir, exist_ok=True)

    with open(os.path.join(out_dir, "web_ui.bin"), "wb") as f:
        f.write(blob)

    # Assembly stub: pull the blob into memory-mapped flash rodata. The absolute
    # path is fine because this file is regenerated (git-ignored) in whatever
    # workspace it is compiled in. ``.rodata.embedded`` is matched by the S3
    # linker's ``.flash.rodata`` (default_rodata_seg / DROM).
    abs_blob = os.path.abspath(blob_path).replace("\\", "/")
    asm = f"""/* Generated by scripts/embed_webui.py -- do not edit. */
    .data
#if !defined(__APPLE__) && !defined(__linux__)
    .section .rodata.embedded
#endif
    .align 4
    .global gWebUiBlobStart
gWebUiBlobStart:
    .incbin "{abs_blob}"
    .global gWebUiBlobEnd
gWebUiBlobEnd:
    .align 4
"""
    with open(os.path.join(out_dir, "web_ui_blob.S"), "w") as f:
        f.write(asm)

    lines = [
        "// Generated by scripts/embed_webui.py -- do not edit.",
        "#pragma once",
        "#include <cstddef>",
        "#include <cstdint>",
        "",
        "// Web UI bundle embedded in firmware flash (see web_ui_blob.S, GM-106).",
        "extern const uint8_t gWebUiBlobStart[];",
        "",
        "struct WebAsset {",
        "    const char *path;        // request path, e.g. \"/assets/app.js\"",
        "    uint32_t offset;         // byte offset into gWebUiBlobStart",
        "    uint32_t length;         // byte length",
        "    const char *contentType; // MIME type",
        "    bool gzip;               // payload is gzip-compressed",
        "};",
        "",
        f"static const WebAsset WEB_ASSETS[] = {{",
    ]
    for e in entries:
        lines.append(
            '    {{"{path}", {offset}u, {length}u, "{ct}", {gz}}},'.format(
                path=c_escape(e["path"]),
                offset=e["offset"],
                length=e["length"],
                ct=c_escape(e["content_type"]),
                gz="true" if e["gzip"] else "false",
            )
        )
    if not entries:
        # A zero-length array is non-standard C++. When no bundle is present (stub
        # build) emit one placeholder; WEB_ASSETS_COUNT stays 0 so it is never read.
        lines.append('    {"", 0u, 0u, "application/octet-stream", false},')
    lines.append("};")
    lines.append("")
    lines.append("static const size_t WEB_ASSETS_COUNT = %du;" % len(entries))
    lines.append('static const char *const WEB_UI_INDEX_PATH = "%s";' % INDEX_PATH)
    lines.append("")
    with open(os.path.join(out_dir, "web_ui_manifest.h"), "w") as f:
        f.write("\n".join(lines))


def pack(src_dir, out_dir):
    assets = collect_assets(src_dir)
    blob = bytearray()
    entries = []
    for url_path, gzip, abs_file in assets:
        with open(abs_file, "rb") as f:
            data = f.read()
        entries.append(
            {
                "path": url_path,
                "offset": len(blob),
                "length": len(data),
                "content_type": content_type_for(url_path),
                "gzip": gzip,
            }
        )
        blob.extend(data)
    # An empty array is invalid in C++; ensure at least one byte so the symbol
    # and the (possibly empty) blob are always well-formed.
    if not blob:
        blob.append(0)
    write_artifacts(out_dir, entries, bytes(blob), os.path.join(out_dir, "web_ui.bin"))
    return entries


def stub(out_dir):
    write_artifacts(out_dir, [], b"\0", os.path.join(out_dir, "web_ui.bin"))


def main(argv):
    parser = argparse.ArgumentParser(description="Embed the web UI into firmware flash.")
    parser.add_argument("--src", help="Built web bundle (e.g. web/dist), gzipped in place")
    parser.add_argument("--out", required=True, help="Output directory for generated artifacts")
    parser.add_argument("--stub", action="store_true", help="Write an empty placeholder bundle")
    args = parser.parse_args(argv)

    if args.stub or not args.src:
        stub(args.out)
        print("embed_webui: wrote empty stub to %s" % args.out)
        return 0

    if not os.path.isdir(args.src):
        print("embed_webui: source dir %s not found" % args.src, file=sys.stderr)
        return 1

    entries = pack(args.src, args.out)
    total = sum(e["length"] for e in entries)
    print("embed_webui: packed %d assets (%d bytes) into %s" % (len(entries), total, args.out))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
