// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: GaggiMate
// Modified: Standby screen replaced with SBB railway clock

#include "../ui.h"
#include <math.h>
#include <stdio.h>

// --- New Timer Types & States ---
typedef enum {
    TIMER_STATE_IDLE,
    TIMER_STATE_EDITING,
    TIMER_STATE_RUNNING,
    TIMER_STATE_FINISHED
} timer_state_t;

typedef enum {
    EDIT_FIELD_HOURS,
    EDIT_FIELD_MINUTES,
    EDIT_FIELD_SECONDS
} edit_field_t;

static timer_state_t current_state = TIMER_STATE_IDLE;
static edit_field_t current_edit_field = EDIT_FIELD_SECONDS;

// Duration values
static int32_t edit_h = 0;
static int32_t edit_m = 0;
static int32_t edit_s = 0;
static int32_t total_duration_secs = 0;
static int32_t remaining_secs = 0;

// New UI Objects
static lv_obj_t *ui_timer_container = NULL;
static lv_obj_t *ui_btn_up = NULL;
static lv_obj_t *ui_btn_down = NULL;
static lv_obj_t *ui_btn_set = NULL;
static lv_obj_t *ui_lbl_h = NULL;
static lv_obj_t *ui_lbl_m = NULL;
static lv_obj_t *ui_lbl_s = NULL;
static lv_obj_t *ui_lbl_colon1 = NULL;
static lv_obj_t *ui_lbl_colon2 = NULL;
static lv_obj_t *ui_timer_arc = NULL;
static lv_timer_t *timer_countdown_job = NULL;

// Forward Declarations
static void update_edit_labels_display(void);
static void timer_countdown_cb(lv_timer_t * t);

void ui_Standby_Timer_Blink_Processor(void);
// --------------------------------------------------------------------------
// UI Interactivity & Event Handlers
// --------------------------------------------------------------------------

lv_obj_t *ui_StandbyScreen = NULL;
lv_obj_t *ui_StandbyScreen_time = NULL;
lv_obj_t *ui_StandbyScreen_statusContainer = NULL;
lv_obj_t *ui_StandbyScreen_wifiIcon = NULL;
lv_obj_t *ui_StandbyScreen_bluetoothIcon = NULL;
lv_obj_t *ui_StandbyScreen_updateIcon = NULL;
lv_obj_t *ui_StandbyScreen_touchIcon = NULL;
lv_obj_t *ui_StandbyScreen_mainLabel = NULL;
lv_obj_t *ui_StandbyScreen_logo = NULL;
lv_obj_t *hour_hand;
lv_obj_t *min_hand;
lv_obj_t *sec_hand;
lv_obj_t *sec_dot;
static lv_obj_t *tick_lines[60];
static lv_point_t tick_pts[60][2];
static lv_point_t min_pts[2];
static lv_point_t sec_pts[2];
static lv_point_t hour_pts[2];
static lv_obj_t *center_dot;
// --------------------------------------------------------------------------
// SBB clock drawing helpers
// --------------------------------------------------------------------------
#define CLOCK_SIZE 240 // canvas px (square)
#define CLOCK_R 360    // outer radius
uint16_t CLOCK_CX = 240;   // centre x
uint16_t CLOCK_CY = 240;  // centre y
static void drawClockTicks(lv_obj_t *parent) {
    for (int i = 0; i < 60; i++) {
        float angle_deg = i * 6.0f;
        float rad = (angle_deg - 90.0f) * (float)M_PI / 180.0f;

        float outer_r, inner_r;
        int width;

        if (i % 5 == 0) {
            outer_r = 220.0f;
            inner_r = 185.0f;
            width = 10;
        } else {
            outer_r = 220.0f;
            inner_r = 210.0f;
            width = 5;
        }

        tick_pts[i][0].x = (int32_t)(CLOCK_CX + inner_r * cosf(rad));
        tick_pts[i][0].y = (int32_t)(CLOCK_CY + inner_r * sinf(rad));
        tick_pts[i][1].x = (int32_t)(CLOCK_CX + outer_r * cosf(rad));
        tick_pts[i][1].y = (int32_t)(CLOCK_CY + outer_r * sinf(rad));

        tick_lines[i] = lv_line_create(parent);
        lv_line_set_points(tick_lines[i], tick_pts[i], 2);
        lv_obj_add_flag(tick_lines[i], LV_OBJ_FLAG_ADV_HITTEST);
        lv_obj_clear_flag(tick_lines[i], LV_OBJ_FLAG_SCROLLABLE);
        ui_object_set_themeable_style_property(
            tick_lines[i], LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_LINE_COLOR,
            _ui_theme_color_NiceWhite);
        ui_object_set_themeable_style_property(
            tick_lines[i], LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_LINE_OPA,
            _ui_theme_alpha_NiceWhite);
        lv_obj_set_style_line_width(tick_lines[i], width, 0);
        lv_obj_set_style_line_rounded(tick_lines[i], false, 0);
    }
}
static lv_obj_t *create_hand(lv_obj_t *parent, lv_color_t color, int width) {
    lv_obj_t *line = lv_line_create(parent);
    if (width == 6) {
        lv_obj_set_style_line_color(line, color, 0);
    } else {
        lv_obj_add_flag(line, LV_OBJ_FLAG_ADV_HITTEST);
        lv_obj_clear_flag(line, LV_OBJ_FLAG_SCROLLABLE);
        ui_object_set_themeable_style_property(
            line, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_LINE_COLOR,
            _ui_theme_color_NiceWhite);
        ui_object_set_themeable_style_property(
            line, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_LINE_OPA,
            _ui_theme_alpha_NiceWhite);
    }
    lv_obj_set_style_line_width(line, width, 0);
    lv_obj_set_style_line_rounded(line, false, 0);

    return line;
}
// static lv_timer_t *clock_timer = NULL;

// Convert polar coords to cartesian (angle in degrees, 0 = 12 o'clock)
static void polar_to_xy(float angle_deg, float radius, int32_t *x_out,
                        int32_t *y_out) {
    float rad = (angle_deg - 90.0f) * (float)M_PI / 180.0f;
    *x_out = (int32_t)(CLOCK_CX + radius * cosf(rad));
    *y_out = (int32_t)(CLOCK_CY + radius * sinf(rad));
}

void ui_Standby_screen_draw_sbb_clock(const struct tm *t) {
    ui_Standby_Timer_Blink_Processor();
    int h = t->tm_hour % 12;
    int m = t->tm_min;
    int s = t->tm_sec;

    // Use floats for smooth movement if desired, otherwise s, m, h
    float sec_angle = s * 6.0f;
    float min_angle = (m + s / 60.0f) * 6.0f;
    float hr_angle = (h + m / 60.0f) * 30.0f;

    int32_t x1, y1, x2, y2;

    // --- SEC HAND ---
    polar_to_xy(sec_angle, 160, &x2, &y2);
    polar_to_xy(sec_angle, -30, &x1, &y1); // Adjusted tail length
    sec_pts[0] = (lv_point_t){x1, y1};
    sec_pts[1] = (lv_point_t){x2, y2};
    lv_line_set_points(sec_hand, sec_pts, 2);
    lv_obj_set_pos(sec_dot, x2 - CLOCK_CX, y2 - CLOCK_CY);

    // --- MIN HAND ---
    polar_to_xy(min_angle, 215, &x2, &y2);
    polar_to_xy(min_angle, -50, &x1, &y1);
    min_pts[0] = (lv_point_t){x1, y1};
    min_pts[1] = (lv_point_t){x2, y2};
    lv_line_set_points(min_hand, min_pts, 2);

    // --- HOUR HAND ---
    polar_to_xy(hr_angle, 160, &x2, &y2);
    polar_to_xy(hr_angle, -40, &x1, &y1);
    hour_pts[0] = (lv_point_t){x1, y1};
    hour_pts[1] = (lv_point_t){x2, y2};
    lv_line_set_points(hour_hand, hour_pts, 2);
}

// --------------------------------------------------------------------------
// event functions
// --------------------------------------------------------------------------
void ui_event_StandbyScreen(lv_event_t *e) {
    lv_event_code_t event_code = lv_event_get_code(e);
    if (event_code == LV_EVENT_CLICKED) {
        onWakeup(e);
    }
}

static void update_edit_labels_display(void) {
    char buf[8];
    sprintf(buf, "%02d", edit_h);
    lv_label_set_text(ui_lbl_h, buf);
    sprintf(buf, "%02d", edit_m);
    lv_label_set_text(ui_lbl_m, buf);
    sprintf(buf, "%02d", edit_s);
    lv_label_set_text(ui_lbl_s, buf);

    // Highlight active element selection
    lv_obj_set_style_text_color(ui_lbl_h, (current_edit_field == EDIT_FIELD_HOURS) ? lv_color_hex(0xE30613) : lv_color_white(), 0);
    lv_obj_set_style_text_color(ui_lbl_m, (current_edit_field == EDIT_FIELD_MINUTES) ? lv_color_hex(0xE30613) : lv_color_white(), 0);
    lv_obj_set_style_text_color(ui_lbl_s, (current_edit_field == EDIT_FIELD_SECONDS) ? lv_color_hex(0xE30613) : lv_color_white(), 0);
}

static void field_click_cb(lv_event_t * e) {
    lv_obj_t * target = lv_event_get_target(e);
    if(target == ui_lbl_h) current_edit_field = EDIT_FIELD_HOURS;
    else if(target == ui_lbl_m) current_edit_field = EDIT_FIELD_MINUTES;
    else if(target == ui_lbl_s) current_edit_field = EDIT_FIELD_SECONDS;
    update_edit_labels_display();
}

static void arrow_click_cb(lv_event_t * e) {
    lv_obj_t * target = lv_event_get_target(e);
    int delta = (target == ui_btn_up) ? 1 : -1;

    if(current_edit_field == EDIT_FIELD_HOURS) {
        edit_h = (edit_h + delta + 24) % 24;
    } else if(current_edit_field == EDIT_FIELD_MINUTES) {
        edit_m = (edit_m + delta + 60) % 60;
    } else if(current_edit_field == EDIT_FIELD_SECONDS) {
        edit_s = (edit_s + delta + 60) % 60;
    }
    update_edit_labels_display();
}

static void set_click_cb(lv_event_t * e) {
    total_duration_secs = (edit_h * 3600) + (edit_m * 60) + edit_s;
    if(total_duration_secs <= 0) return; // Prevent zero second runs

    remaining_secs = total_duration_secs;
    current_state = TIMER_STATE_RUNNING;

    // Transition elements visibility
    lv_obj_add_flag(ui_btn_up, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_btn_down, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_btn_set, LV_OBJ_FLAG_HIDDEN);

    // Clear dynamic styles to lock uniform run colors
    lv_obj_set_style_text_color(ui_lbl_h, lv_color_white(), 0);
    lv_obj_set_style_text_color(ui_lbl_m, lv_color_white(), 0);
    lv_obj_set_style_text_color(ui_lbl_s, lv_color_white(), 0);

    // Configure and reveal Dial Track Arc
    lv_arc_set_value(ui_timer_arc, 360);
    lv_obj_clear_flag(ui_timer_arc, LV_OBJ_FLAG_HIDDEN);

    // Start running high-priority loop ticking
    if(!timer_countdown_job) {
        timer_countdown_job = lv_timer_create(timer_countdown_cb, 1000, NULL);
    } else {
        lv_timer_resume(timer_countdown_job);
    }
}

// Global Touch Icon trigger target callback inside main code
void ui_event_TouchIcon_Clicked(lv_event_t * e) {
    if(current_state == TIMER_STATE_IDLE) {
        current_state = TIMER_STATE_EDITING;
        lv_obj_add_flag(ui_StandbyScreen_touchIcon, LV_OBJ_FLAG_HIDDEN);
        
        // Show editing structure components
        lv_obj_clear_flag(ui_timer_container, LV_OBJ_FLAG_HIDDEN);
        lv_obj_clear_flag(ui_btn_up, LV_OBJ_FLAG_HIDDEN);
        lv_obj_clear_flag(ui_btn_down, LV_OBJ_FLAG_HIDDEN);
        lv_obj_clear_flag(ui_btn_set, LV_OBJ_FLAG_HIDDEN);
        
        current_edit_field = EDIT_FIELD_SECONDS; // Default focus target
        update_edit_labels_display();
    }
}

// Container click to handle clearing completed alert
static void container_click_cb(lv_event_t * e) {
    if(current_state == TIMER_STATE_FINISHED) {
        current_state = TIMER_STATE_IDLE;
        
        // Clean layout resets
        lv_obj_add_flag(ui_timer_container, LV_OBJ_FLAG_HIDDEN);
        lv_obj_set_style_opa(ui_timer_container, LV_OPA_COVER, 0); // Remove Blink visibility attributes
        lv_obj_add_flag(ui_timer_arc, LV_OBJ_FLAG_HIDDEN);
        
        // Reset defaults variables 
        edit_h = 0; edit_m = 0; edit_s = 0;

        // Bring back standby Touch Icon target
        lv_obj_clear_flag(ui_StandbyScreen_touchIcon, LV_OBJ_FLAG_HIDDEN);
    }
}

// --------------------------------------------------------------------------
// Core Runtime Processing Logic
// --------------------------------------------------------------------------

static void timer_countdown_cb(lv_timer_t * t) {
    if(current_state != TIMER_STATE_RUNNING) return;

    remaining_secs--;

    if(remaining_secs <= 0) {
        // Complete execution state
        current_state = TIMER_STATE_FINISHED;
        lv_arc_set_value(ui_timer_arc, 0);
        lv_timer_pause(timer_countdown_job);
        return;
    }

    // Refresh digits numbers
    int32_t h = remaining_secs / 3600;
    int32_t m = (remaining_secs % 3600) / 60;
    int32_t s = remaining_secs % 60;

    char buf[8];
    sprintf(buf, "%02d", h); lv_label_set_text(ui_lbl_h, buf);
    sprintf(buf, "%02d", m); lv_label_set_text(ui_lbl_m, buf);
    sprintf(buf, "%02d", s); lv_label_set_text(ui_lbl_s, buf);

    // Sync Red Visual Arc representation (360 -> 0 Degrees tracking layout)
    int32_t arc_val = (remaining_secs * 360) / total_duration_secs;
    lv_arc_set_value(ui_timer_arc, arc_val);
}

// Inject inside your system update tickers execution threads loop (e.g. 100ms / 500ms loop context)
void ui_Standby_Timer_Blink_Processor(void) {
    if(current_state == TIMER_STATE_FINISHED) {
        // Handle alternating blinking visibility
        static uint32_t last_toggle = 0;
        if(lv_tick_elaps(last_toggle) > 500) {
            last_toggle = lv_tick_get();
            lv_opa_t current_opa = lv_obj_get_style_opa(ui_timer_container, 0);
            lv_obj_set_style_opa(ui_timer_container, (current_opa == LV_OPA_TRANSP) ? LV_OPA_COVER : LV_OPA_TRANSP, 0);
        }
    }
}

// --------------------------------------------------------------------------
// Layout Construction Instantiation
// --------------------------------------------------------------------------

void ui_Init_Timer_Addon(lv_obj_t *parent) {
    // 1. Red Progress Ring Overlay (Layered right above SBB ticks)
    ui_timer_arc = lv_arc_create(parent);
    lv_obj_set_size(ui_timer_arc, 450, 450); // Covers ticks (outer_r = 220)
    lv_obj_center(ui_timer_arc);
    lv_arc_set_rotation(ui_timer_arc, 270); // Starts right at 12 o'clock top
    lv_arc_set_bg_angles(ui_timer_arc, 0, 360);
    lv_arc_set_range(ui_timer_arc, 0, 360);
    lv_obj_add_flag(ui_timer_arc, LV_OBJ_FLAG_HIDDEN);
    
    // Clear back styling tracks out to show only custom running values
    lv_obj_set_style_arc_width(ui_timer_arc, 0, LV_PART_MAIN); 
    lv_obj_set_style_arc_width(ui_timer_arc, 3, LV_PART_INDICATOR);
    lv_obj_set_style_arc_color(ui_timer_arc, lv_color_hex(0xE30613), LV_PART_INDICATOR);
    lv_obj_remove_style(ui_timer_arc, NULL, LV_PART_KNOB); // Hide standard drag-knobs

    // 2. Base Container for Countdown Elements (Where TouchIcon rests at Y: 120)
    ui_timer_container = lv_obj_create(parent);
    lv_obj_remove_style_all(ui_timer_container);
    lv_obj_set_size(ui_timer_container, 200, 60);
    lv_obj_set_pos(ui_timer_container, 0, 120);
    lv_obj_set_align(ui_timer_container, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_timer_container, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_timer_container, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_add_event_cb(ui_timer_container, container_click_cb, LV_EVENT_CLICKED, NULL);

    // Flex items positioning layout for digits
    lv_obj_set_flex_flow(ui_timer_container, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_timer_container, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);

    // Init Label Digits
    ui_lbl_h = lv_label_create(ui_timer_container);
    ui_lbl_colon1 = lv_label_create(ui_timer_container);
    ui_lbl_m = lv_label_create(ui_timer_container);
    ui_lbl_colon2 = lv_label_create(ui_timer_container);
    ui_lbl_s = lv_label_create(ui_timer_container);

    lv_label_set_text(ui_lbl_colon1, ":");
    lv_label_set_text(ui_lbl_colon2, ":");

    lv_obj_t *labels[] = {ui_lbl_h, ui_lbl_colon1, ui_lbl_m, ui_lbl_colon2, ui_lbl_s};
    for(int i = 0; i < 5; i++) {
        lv_obj_set_style_text_font(labels[i], &lv_font_montserrat_24, 0);
        lv_obj_set_style_text_color(labels[i], lv_color_white(), 0);
        if(i % 2 == 0) { // Make editable fields interactive
            lv_obj_add_flag(labels[i], LV_OBJ_FLAG_CLICKABLE);
            lv_obj_add_event_cb(labels[i], field_click_cb, LV_EVENT_CLICKED, NULL);
        }
    }

    // 3. Arrow Control Buttons (Offset right and left borders gracefully)
    ui_btn_up = lv_btn_create(parent);
    lv_obj_set_size(ui_btn_up, 45, 40);
    lv_obj_set_pos(ui_btn_up, -110, 120);
    lv_obj_set_align(ui_btn_up, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btn_up, LV_OBJ_FLAG_HIDDEN);
    ui_object_set_themeable_style_property(
        ui_btn_up, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
        _ui_theme_color_Dark
    );
    ui_object_set_themeable_style_property(
        ui_btn_up, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
        _ui_theme_alpha_Dark
    );
    lv_obj_t *lbl_up = lv_label_create(ui_btn_up);
    lv_label_set_text(lbl_up, LV_SYMBOL_UP);
    lv_obj_center(lbl_up);
    lv_obj_add_event_cb(ui_btn_up, arrow_click_cb, LV_EVENT_CLICKED, NULL);
    ui_btn_down = lv_btn_create(parent);
    lv_obj_set_size(ui_btn_down, 45, 40);
    lv_obj_set_pos(ui_btn_down, 110, 120);
    lv_obj_set_align(ui_btn_down, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btn_down, LV_OBJ_FLAG_HIDDEN);
    ui_object_set_themeable_style_property(
        ui_btn_down, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
        _ui_theme_color_Dark
    );
    ui_object_set_themeable_style_property(
        ui_btn_down, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
        _ui_theme_alpha_Dark
    );
    lv_obj_t *lbl_down = lv_label_create(ui_btn_down);
    lv_label_set_text(lbl_down, LV_SYMBOL_DOWN);
    lv_obj_center(lbl_down);
    lv_obj_add_event_cb(ui_btn_down, arrow_click_cb, LV_EVENT_CLICKED, NULL);

    ui_btn_set = lv_btn_create(parent);
    lv_obj_set_size(ui_btn_set, 55, 35);
    lv_obj_set_pos(ui_btn_set, 0, 175); // Sits underneath layout values fields
    lv_obj_set_align(ui_btn_set, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btn_set, LV_OBJ_FLAG_HIDDEN);
    ui_object_set_themeable_style_property(
        ui_btn_set, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
        _ui_theme_color_Dark
    );
    ui_object_set_themeable_style_property(
        ui_btn_set, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
        _ui_theme_alpha_Dark
    );
    lv_obj_t *lbl_set = lv_label_create(ui_btn_set);
    lv_label_set_text(lbl_set, LV_SYMBOL_OK " SET");
    lv_obj_center(lbl_set);
    lv_obj_add_event_cb(ui_btn_set, set_click_cb, LV_EVENT_CLICKED, NULL);
}
// --------------------------------------------------------------------------
// build functions
// --------------------------------------------------------------------------
void ui_StandbyScreen_screen_init(void) {
    int32_t screen_w = lv_disp_get_hor_res(NULL);
    int32_t screen_h = lv_disp_get_ver_res(NULL);
    CLOCK_CX = screen_w / 2;
    CLOCK_CY = screen_h / 2;
    ui_StandbyScreen = lv_obj_create(NULL);
    lv_obj_set_width(ui_StandbyScreen, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_StandbyScreen, LV_SIZE_CONTENT);
    lv_obj_set_align(ui_StandbyScreen, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_StandbyScreen, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_add_event_cb(ui_StandbyScreen, scr_unloaded_delete_cb,
                        LV_EVENT_SCREEN_UNLOADED,
                        ui_StandbyScreen_screen_destroy);
    ui_object_set_themeable_style_property(
        ui_StandbyScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
        _ui_theme_color_Dark);

    // Start 1-second refresh timer
    // clock_timer = lv_timer_create(clock_timer_cb, 1000, NULL);

    // --- time label (hidden by default, shown after wakeup) ---
    ui_StandbyScreen_time = lv_label_create(ui_StandbyScreen);
    lv_obj_set_width(ui_StandbyScreen_time, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_StandbyScreen_time, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_StandbyScreen_time, 0);
    lv_obj_set_y(ui_StandbyScreen_time, -140);
    lv_obj_set_align(ui_StandbyScreen_time, LV_ALIGN_CENTER);
    lv_label_set_text(ui_StandbyScreen_time, "0:00");
    lv_obj_add_flag(ui_StandbyScreen_time, LV_OBJ_FLAG_HIDDEN);
    ui_object_set_themeable_style_property(
        ui_StandbyScreen_time, LV_PART_MAIN | LV_STATE_DEFAULT,
        LV_STYLE_TEXT_COLOR, _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(
        ui_StandbyScreen_time, LV_PART_MAIN | LV_STATE_DEFAULT,
        LV_STYLE_TEXT_OPA, _ui_theme_alpha_NiceWhite);
    lv_obj_set_style_text_align(ui_StandbyScreen_time, LV_TEXT_ALIGN_CENTER,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_StandbyScreen_time, &lv_font_montserrat_34,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    // --- status icon container ---
    ui_StandbyScreen_statusContainer = lv_obj_create(ui_StandbyScreen);
    lv_obj_remove_style_all(ui_StandbyScreen_statusContainer);
    lv_obj_set_width(ui_StandbyScreen_statusContainer, 300);
    lv_obj_set_height(ui_StandbyScreen_statusContainer, 20);
    lv_obj_set_x(ui_StandbyScreen_statusContainer, 0);
    lv_obj_set_y(ui_StandbyScreen_statusContainer, -140);
    lv_obj_set_align(ui_StandbyScreen_statusContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_StandbyScreen_statusContainer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_StandbyScreen_statusContainer,
                          LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_StandbyScreen_statusContainer, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_StandbyScreen_statusContainer,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);

    // wifi icon
    ui_StandbyScreen_wifiIcon = lv_img_create(ui_StandbyScreen_statusContainer);
    lv_img_set_src(ui_StandbyScreen_wifiIcon, &ui_img_364513079);
    lv_obj_set_width(ui_StandbyScreen_wifiIcon, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_StandbyScreen_wifiIcon, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_StandbyScreen_wifiIcon, 20);
    lv_obj_set_y(ui_StandbyScreen_wifiIcon, -140);
    lv_obj_set_align(ui_StandbyScreen_wifiIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_StandbyScreen_wifiIcon, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(ui_StandbyScreen_wifiIcon, LV_OBJ_FLAG_SCROLLABLE);
    ui_object_set_themeable_style_property(
        ui_StandbyScreen_wifiIcon, LV_PART_MAIN | LV_STATE_DEFAULT,
        LV_STYLE_BORDER_COLOR, _ui_theme_color_Dark);
    ui_object_set_themeable_style_property(
        ui_StandbyScreen_wifiIcon, LV_PART_MAIN | LV_STATE_DEFAULT,
        LV_STYLE_BORDER_OPA, _ui_theme_alpha_Dark);
    lv_obj_set_style_border_width(ui_StandbyScreen_wifiIcon, 10,
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(
        ui_StandbyScreen_wifiIcon, LV_PART_MAIN | LV_STATE_DEFAULT,
        LV_STYLE_IMG_RECOLOR, _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(
        ui_StandbyScreen_wifiIcon, LV_PART_MAIN | LV_STATE_DEFAULT,
        LV_STYLE_IMG_RECOLOR_OPA, _ui_theme_alpha_NiceWhite);

    // bluetooth icon
    ui_StandbyScreen_bluetoothIcon =
        lv_img_create(ui_StandbyScreen_statusContainer);
    lv_img_set_src(ui_StandbyScreen_bluetoothIcon, &ui_img_1091371356);
    lv_obj_set_width(ui_StandbyScreen_bluetoothIcon, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_StandbyScreen_bluetoothIcon, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_StandbyScreen_bluetoothIcon, -20);
    lv_obj_set_y(ui_StandbyScreen_bluetoothIcon, -140);
    lv_obj_set_align(ui_StandbyScreen_bluetoothIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_StandbyScreen_bluetoothIcon, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(ui_StandbyScreen_bluetoothIcon, LV_OBJ_FLAG_SCROLLABLE);
    ui_object_set_themeable_style_property(
        ui_StandbyScreen_bluetoothIcon, LV_PART_MAIN | LV_STATE_DEFAULT,
        LV_STYLE_BORDER_COLOR, _ui_theme_color_Dark);
    ui_object_set_themeable_style_property(
        ui_StandbyScreen_bluetoothIcon, LV_PART_MAIN | LV_STATE_DEFAULT,
        LV_STYLE_BORDER_OPA, _ui_theme_alpha_Dark);
    lv_obj_set_style_border_width(ui_StandbyScreen_bluetoothIcon, 10,
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(
        ui_StandbyScreen_bluetoothIcon, LV_PART_MAIN | LV_STATE_DEFAULT,
        LV_STYLE_IMG_RECOLOR, _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(
        ui_StandbyScreen_bluetoothIcon, LV_PART_MAIN | LV_STATE_DEFAULT,
        LV_STYLE_IMG_RECOLOR_OPA, _ui_theme_alpha_NiceWhite);

    // update icon
    ui_StandbyScreen_updateIcon =
        lv_img_create(ui_StandbyScreen_statusContainer);
    lv_img_set_src(ui_StandbyScreen_updateIcon, &ui_img_1765671371);
    lv_obj_set_width(ui_StandbyScreen_updateIcon, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_StandbyScreen_updateIcon, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_StandbyScreen_updateIcon, -20);
    lv_obj_set_y(ui_StandbyScreen_updateIcon, -140);
    lv_obj_set_align(ui_StandbyScreen_updateIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_StandbyScreen_updateIcon, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(ui_StandbyScreen_updateIcon, LV_OBJ_FLAG_SCROLLABLE);
    ui_object_set_themeable_style_property(
        ui_StandbyScreen_updateIcon, LV_PART_MAIN | LV_STATE_DEFAULT,
        LV_STYLE_BORDER_COLOR, _ui_theme_color_Dark);
    ui_object_set_themeable_style_property(
        ui_StandbyScreen_updateIcon, LV_PART_MAIN | LV_STATE_DEFAULT,
        LV_STYLE_BORDER_OPA, _ui_theme_alpha_Dark);
    lv_obj_set_style_border_width(ui_StandbyScreen_updateIcon, 10,
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(
        ui_StandbyScreen_updateIcon, LV_PART_MAIN | LV_STATE_DEFAULT,
        LV_STYLE_IMG_RECOLOR, _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(
        ui_StandbyScreen_updateIcon, LV_PART_MAIN | LV_STATE_DEFAULT,
        LV_STYLE_IMG_RECOLOR_OPA, _ui_theme_alpha_NiceWhite);

    drawClockTicks(ui_StandbyScreen);
    // touch icon
    ui_StandbyScreen_touchIcon = lv_img_create(ui_StandbyScreen);
    lv_img_set_src(ui_StandbyScreen_touchIcon, &ui_img_1732953241);
    lv_obj_set_width(ui_StandbyScreen_touchIcon, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_StandbyScreen_touchIcon, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_StandbyScreen_touchIcon, 0);
    lv_obj_set_y(ui_StandbyScreen_touchIcon, 120);
    lv_obj_set_align(ui_StandbyScreen_touchIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_StandbyScreen_touchIcon,
                    LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(ui_StandbyScreen_touchIcon, LV_OBJ_FLAG_SCROLLABLE);
    lv_img_set_zoom(ui_StandbyScreen_touchIcon, 210);
// Bind event callback to the Touch icon
lv_obj_add_flag(ui_StandbyScreen_touchIcon, LV_OBJ_FLAG_CLICKABLE);
lv_obj_add_event_cb(ui_StandbyScreen_touchIcon, ui_event_TouchIcon_Clicked, LV_EVENT_CLICKED, NULL);

// Instantiate components layout
ui_Init_Timer_Addon(ui_StandbyScreen);
    // main label

    ui_object_set_themeable_style_property(
        ui_StandbyScreen_touchIcon, LV_PART_MAIN | LV_STATE_DEFAULT,
        LV_STYLE_IMG_RECOLOR, _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(
        ui_StandbyScreen_touchIcon, LV_PART_MAIN | LV_STATE_DEFAULT,
        LV_STYLE_IMG_RECOLOR_OPA, _ui_theme_alpha_NiceWhite);
    ui_StandbyScreen_logo = lv_img_create(ui_StandbyScreen);
    lv_img_set_src(ui_StandbyScreen_logo, &ui_img_logo_png);
    lv_obj_set_width(ui_StandbyScreen_logo, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_StandbyScreen_logo, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_StandbyScreen_logo, LV_ALIGN_CENTER);
    lv_obj_set_y(ui_StandbyScreen_logo, -100);
    lv_obj_add_flag(ui_StandbyScreen_logo, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_StandbyScreen_logo, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_img_set_zoom(ui_StandbyScreen_logo, 80);
    ui_object_set_themeable_style_property(
        ui_StandbyScreen_logo, LV_PART_MAIN | LV_STATE_DEFAULT,
        LV_STYLE_IMG_RECOLOR, _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(
        ui_StandbyScreen_logo, LV_PART_MAIN | LV_STATE_DEFAULT,
        LV_STYLE_IMG_RECOLOR_OPA, _ui_theme_alpha_Dark);
    ui_StandbyScreen_mainLabel = lv_label_create(ui_StandbyScreen);
    lv_obj_set_width(ui_StandbyScreen_mainLabel, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_StandbyScreen_mainLabel, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_StandbyScreen_mainLabel, 0);
    lv_obj_set_y(ui_StandbyScreen_mainLabel, 120);
    lv_obj_set_align(ui_StandbyScreen_mainLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_StandbyScreen_mainLabel, "Starting...");
    ui_object_set_themeable_style_property(
        ui_StandbyScreen_mainLabel, LV_PART_MAIN | LV_STATE_DEFAULT,
        LV_STYLE_TEXT_COLOR, _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(
        ui_StandbyScreen_mainLabel, LV_PART_MAIN | LV_STATE_DEFAULT,
        LV_STYLE_TEXT_OPA, _ui_theme_alpha_NiceWhite);
    lv_obj_set_style_text_font(ui_StandbyScreen_mainLabel,
                               &lv_font_montserrat_20,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    hour_hand = create_hand(ui_StandbyScreen, lv_color_black(), 18);
    min_hand = create_hand(ui_StandbyScreen, lv_color_black(), 14);
    sec_hand = create_hand(ui_StandbyScreen, lv_color_hex(0xE30613), 6);
    sec_dot = lv_obj_create(ui_StandbyScreen);
    lv_obj_set_width(sec_dot, 25);
    lv_obj_set_height(sec_dot, 25);
    lv_obj_set_align(sec_dot, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(sec_dot, LV_RADIUS_CIRCLE, 0);
    lv_obj_set_style_bg_color(sec_dot, lv_color_hex(0xE30613), 0);
    lv_obj_set_style_border_width(sec_dot, 0, 0);
    lv_obj_clear_flag(sec_dot, LV_OBJ_FLAG_SCROLLABLE);
    center_dot = lv_obj_create(ui_StandbyScreen);
    lv_obj_set_width(center_dot, 10);
    lv_obj_set_height(center_dot, 10);
    lv_obj_set_align(center_dot, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(center_dot, LV_RADIUS_CIRCLE, 0);
    lv_obj_set_style_bg_color(center_dot, lv_color_hex(0xE30613), 0);
    lv_obj_set_style_border_width(center_dot, 0, 0);
    lv_obj_clear_flag(center_dot, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_add_event_cb(ui_StandbyScreen, ui_event_StandbyScreen, LV_EVENT_ALL,
                        NULL);
}

void ui_StandbyScreen_screen_destroy(void) {
    // Stop the clock timer before destroying the screen
    if (ui_StandbyScreen)
        lv_obj_del(ui_StandbyScreen);

    ui_StandbyScreen = NULL;
    ui_StandbyScreen_logo = NULL;
    hour_hand = NULL;
    min_hand = NULL;
    sec_hand = NULL;
    sec_dot = NULL;
    center_dot = NULL;
    for (int i = 0; i < 60; i++) {
        tick_lines[i] = NULL;
    }
    ui_StandbyScreen_time = NULL;
    ui_StandbyScreen_statusContainer = NULL;
    ui_StandbyScreen_wifiIcon = NULL;
    ui_StandbyScreen_bluetoothIcon = NULL;
    ui_StandbyScreen_updateIcon = NULL;
    ui_StandbyScreen_touchIcon = NULL;
    ui_StandbyScreen_mainLabel = NULL;
}